---
- include_tasks: Linux/Installation-Tasks.yml
  when: ansible_os_family == 'RedHat' or ansible_os_family == 'Debian'

- include_tasks: Windows/Installation-Tasks.yml
  when: ansible_os_family == 'Windows'