---
- name: Decompress Denodo Monitor
  community.windows.win_unzip:
    dest: "{{ solution_manager_installer.install_path }}/tools/monitor"
    recurse: yes
    src: "{{ solution_manager_installer.denodo_installer_path }}/tools/monitor/denodo-monitor.zip"
