---
- include_tasks: Installer-OS-Family-RedHat-Tasks.yml
  when: ansible_os_family == 'RedHat'

- name: Create denodo sub-directory
  ansible.builtin.file:
    path: "{{ solution_manager_installer.denodo_root_directory }}"
    state: directory

- name: Upload and decompress install file
  ansible.builtin.unarchive:
    creates: "{{ solution_manager_installer.denodo_root_directory }}/solution_manager_installer"
    dest: "{{ solution_manager_installer.denodo_root_directory }}"
    src: "{{ solution_manager_installer.denodo_installer_path }}"

- name: Add install config xml
  ansible.builtin.template:
    dest: "{{ solution_manager_installer.denodo_root_directory }}/solution_manager_installer/installer.xml"
    src: linux_installer.j2

