---
- name: Copy service shell to systemd location
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "/etc/systemd/system/{{ item.path | basename | regex_replace('\.j2', '\.service') }}"
  with_fileglob:
    - "systemd/*"

- name: Start Denodo License Manager
  ansible.builtin.systemd:
    daemon_reload: yes
    enabled: yes
    name: denodo-license-manager.service
    state: started

- name: Start Denodo Solution Manager
  ansible.builtin.systemd:
    daemon_reload: yes
    enabled: yes
    name: denodo-solution-manager.service
    state: started

- name: Start Denodo Solution Manager Web Tool
  ansible.builtin.systemd:
    daemon_reload: yes
    enabled: yes
    name: denodo-solution-manager-web-tool.service
    state: started